name: Context Workflow
# This workflow demonstrates how to access and dump various contexts in GitHub Actions.
on: 
  workflow_dispatch:
  push:

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump secrets context
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: echo "$SECRETS_CONTEXT"
      - name: check if the job context is successful
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "Job status is successful"
          else
            echo "Job status is not successful"
            exit 1
          fi

  deploy_job:
    needs: dump_contexts_to_log
    if: ${{ github.ref == 'refs/heads/main' }}
    # This job will only run if the ref is main branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Only run if the ref is main branch
        run: echo "This job will only run if the ref is main branch"
      
      - name: Print the current branch
        run: echo "Current branch is:" " ${{ github.ref }}"