# This is a GitHub Actions workflow file that generates ASCII art, executes a shell script,
# The idea is to demonstrate how to use cron jobs in GitHub Actions,
# allowing the job to run at scheduled intervals (e.g., every minute).
# It consists of a single job that prints a message every minute.
# The cron job is triggered by a workflow_dispatch event, allowing manual execution.

name: Cron Job Workflow
# The idea is to demonstrate how to use cron jobs in GitHub Actions,

on:
  workflow_dispatch:
    inputs:
      run_now:
        description: 'Run the cron job immediately'
        required: false
        default: 'false'
#   schedule:
#     - cron: '* * * * *'  # This cron expression runs the job every minute
jobs:
  cron_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cron job action
        run: |
          echo "Print Hi this is a cron job that runs every minute"