# This is a GitHub Actions workflow file that generates ASCII art, executes a shell script,
# The idea is to demonstrate how to create a simple workflow with multiple jobs,
# and runs a Python script to display ASCII art. It consists of two jobs: first_job and second_job.
# Also uses the trufflesecurity/trufflehog action for secret scanning.
name: First Workflow

on: push

jobs: 
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome to my first workflow
        run: echo "Hello, world!"

      - name: List out all the files
        run: ls -la

      - name: Print the current date
        run: date

  second_job:
    runs-on: ubuntu-latest
    needs: first_job
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: This is the second job
        run: echo "This is the second job, which runs after the first job."

      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown
