name: "Giphy"

on: 
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  issues: write
  pull-requests: write
    
jobs:
  giphy:
    runs-on: ubuntu-latest
    steps:
    - uses: mkramb/giphy-action@master
      with:
        giphy-secret: ${{ secrets.GIPHY_API_KEY }}
        github-secret: ${{ secrets.GITHUB_TOKEN }}
