name: Go CI with Caching

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-go:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug ls root
        run: ls -la

      - name: Debug ls go-app
        run: ls -la go-app

      - name: Check go.mod
        run: cat go-app/go.mod

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
    
      - name: Debug go.sum location
        run: ls -l go-app/go.sum

      - name: Cache Go Modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go-app/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download Dependencies
        run: go mod download
        working-directory: go-app

      - name: Build
        run: go build -o app
        working-directory: go-app

      - name: Run Application
        run: ./app
        working-directory: go-app

      - name: Run Tests
        run: go test ./...
        working-directory: go-app
    
  docker-build:
    runs-on: ubuntu-latest
    needs: build-go

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
    
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GH_PAT }}
        
      - name: Docker login success
        run: echo "Docker login successful"
    
      - name: Build Docker Image
        run: docker build -t ghcr.io/dexroku/go-app:latest .
        working-directory: go-app