name: Kubernetes Go App Workflow with cache and Docker
# This workflow builds a Go application, runs tests, builds a Docker image, and deploys it to Kubernetes clusters using kind.

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-go:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug ls root
        run: ls -la

      - name: Debug ls go-app
        run: ls -la go-app

      - name: Check go.mod
        run: cat go-app/go.mod

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
    
      - name: Debug go.sum location
        run: ls -l go-app/go.sum

      - name: Cache Go Modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go-app/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download Dependencies
        run: go mod download
        working-directory: go-app

      - name: Build
        run: go build -o app
        working-directory: go-app

      - name: Run Application
        run: ./app
        working-directory: go-app

      - name: Run Tests
        run: go test ./...
        working-directory: go-app
    
  docker-build:
    runs-on: ubuntu-latest
    needs: build-go

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
    
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: "${{ secrets.USERNAME }}"
          password: "${{ secrets.PASSWORD }}"
        
      - name: Docker login success
        run: echo "Docker login successful"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
            context: go-app
            push: true
            tags: roku15/go-app:latest

  dev-deploy:
    if: contains(github.ref, 'refs/heads/feature')
    runs-on: ubuntu-latest
    needs: docker-build
    env:
      KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker kind
        uses: docker/setup-buildx-action@v2
    
      - name: Install kind 
        run: |
          curl -sLo ./kind https://kind.sigs.k8s.io/dl/v0.17.0/kind-$(uname)-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
        
      - name: Create kind test cluster
        run: |
          kind create cluster --name dev-cluster --wait 60s
          kubectl cluster-info --context kind-dev-cluster

      - name: Create kind prod cluster
        run: |
          kind create cluster --name prod-cluster --wait 60s
          kubectl cluster-info --context kind-prod-cluster

      - name: Pull Docker Image
        run: docker pull roku15/go-app:latest

      - name: Load Docker Image into kind
        run: kind load docker-image roku15/go-app:latest --name dev-cluster

      - name: Load Docker Image into kind prod
        run: kind load docker-image roku15/go-app:latest --name prod-cluster
      
      - name: Deploy go app to dev cluster
        working-directory: k8s/test
        run: |
          kubectl apply -f deployment.yml --context kind-dev-cluster
          kubectl apply -f service.yml --context kind-dev-cluster
          kubectl get deployment 

      - name: Deploy go app to prod cluster
        working-directory: k8s/prod
        run: |
          kubectl apply -f deployment.yml --context kind-prod-cluster
          kubectl apply -f service.yml --context kind-prod-cluster
          kubectl get deployment 

  prod-deploy:
    if: contains(github.ref, 'refs/heads/main')
    runs-on: ubuntu-latest
    needs: docker-build
    env:
      KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker kind
        uses: docker/setup-buildx-action@v2
    
      - name: Install kind 
        run: |
          curl -sLo ./kind https://kind.sigs.k8s.io/dl/v0.17.0/kind-$(uname)-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
        
      - name: Create kind prod cluster
        run: |
          kind create cluster --name prod-cluster --wait 60s
          kubectl cluster-info --context kind-prod-cluster

      - name: Pull Docker Image
        run: docker pull roku15/go-app:latest

      - name: Load Docker Image into kind prod
        run: kind load docker-image roku15/go-app:latest --name prod-cluster
      
      - name: Deploy go app to prod cluster
        working-directory: k8s/prod
        run: |
          kubectl apply -f deployment.yml --context kind-prod-cluster
          kubectl apply -f service.yml --context kind-prod-cluster
          kubectl get deployment