name: Poll Solar System

on:
  schedule:
    - cron: '* * * * *'  # This cron expression runs the job every minute
  workflow_dispatch:

jobs:
  poll_solar_system:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest commit from solar-system repo
        id: get_latest_commit
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const { data: commits } = await github.rest.repos.listCommits({
              owner: 'DexRoku',
              repo: 'solar-system',
              per_page: 1,
            });
            return commits[0].sha;

      - name: Check if commit has changed
        id: check_commit
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const latestCommit = '${{ steps.get_latest_commit.outputs.result }}';
            const previousCommit = '${{ github.event.inputs.previous_commit }}';

            return latestCommit !== previousCommit;

      - name: Trigger Solar System Workflow
        if: steps.check_commit.outputs.result == 'true'
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            https://api.github.com/repos/DexRoku/solar-system/actions/workflows/solar-system.yml/dispatches \
            -d '{"ref":"main"}'

    