name: Generate ASCII Art

on: push

jobs:
  ascii_art_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Execute the shell script
        run: |
          chmod +x .github/workflows/ascii-script.sh
          .github/workflows/ascii-script.sh
