name: Generate ASCII Art

on: push

jobs: 
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Generate ASCII Art
        run: |
          echo "Generating ASCII art..."
          echo "  _    _ _           _   _       " 
          echo " | |  | (_)         | | (_)      "
          echo " | |  | |_ _ __   __| |_ _  __ _ "
          echo " | |  | | | '_ \ / _\` | | |/ _\` |"
          echo " | |__| | | | | | (_| | | | (_| |"
          echo "  \____/|_|_| |_|\__,_|_|_|\__,_|"
          echo "ASCII art generated successfully!"
      
      - name: Execute the shell script
        run: |
          chmod +x .github/workflows/ascii-script.sh
          .github/workflows/ascii-script.sh
      
      - name: Sleep for 5 seconds
        run: sleep 5
  
  test_job_2:
    runs-on: ubuntu-latest
    needs: build_job_1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List all files for debugging
        run: ls -laR
  
      - name: Check if the file exists
        run: |
          if [ -f .github/workflows/ascii-script.sh ]; then
            echo "File exists."
          else
            echo "File does not exist."
            exit 1
          fi
  
  deploy_job_3:
    runs-on: ubuntu-latest
    needs: test_job_2
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run the shell script 
        run: |
          chmod +x .github/workflows/ascii-script.sh
          .github/workflows/ascii-script.sh

      - name: Deploy the application
        run: echo "Deploying the application..."
      
      - name: Finalize deployment
        run: echo "Deployment completed successfully!"