name: Generate ASCII Art

on: push

jobs: 
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Generate ASCII Art
        run: |
          echo "Generating ASCII art..."
          echo "  _    _ _           _   _       " 
          echo " | |  | (_)         | | (_)      "
          echo " | |  | |_ _ __   __| |_ _  __ _ "
          echo " | |  | | | '_ \ / _\` | | |/ _\` |"
          echo " | |__| | | | | | (_| | | | (_| |"
          echo "  \____/|_|_| |_|\__,_|_|_|\__,_|"
          echo "ASCII art generated successfully!"
      
      - name: Execute the shell script
        run: |
          chmod +x .github/workflows/ascii-script.sh
          .github/workflows/ascii-script.sh
        
      - name: Display the generated ASCII art
        run: |
          echo "Displaying the generated ASCII art:"
          cat ascii_output.txt

      - name: Sleep for 5 seconds
        run: sleep 5
      
      - name: upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ascii-output
          path: ascii_output.txt

  test_job_2:
    runs-on: ubuntu-latest
    needs: build_job_1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List all files for debugging
        run: ls -laR
  
      - name: Check if the file exists
        run: |
          if [ -f .github/workflows/ascii-script.sh ]; then
            echo "File exists."
          else
            echo "File does not exist."
            exit 1
          fi
      
      - name: Display the downloaded artifact
        uses: actions/download-artifact@v4
        with:
          name: ascii-output
      
      - name: Display the ASCII art from the artifact
        run: |
          echo "Displaying the ASCII art from the artifact:"
          cat ascii_output.txt
      
  deploy_job_3:
    runs-on: ubuntu-latest
    needs: test_job_2
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run the shell script 
        run: |
          chmod +x .github/workflows/ascii-script.sh
          .github/workflows/ascii-script.sh

      - name: Deploy the application
        run: echo "Deploying the application..."
      
      - name: Finalize deployment
        run: echo "Deployment completed successfully!"

      - name: Sleep for 5 seconds
        run: sleep 5

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
            
      - name: Install pyfiglet
        run: pip install pyfiglet
      
      - name: list all files for debugging
        run: ls -laR
      
      - name: check if ASCII art script exists
        run: |
          if [ -f ascii-art.py ]; then
            echo "ASCII art script exists."
          else
            echo "ASCII art script does not exist."
            exit 1
          fi

      - name: Run ASCII art script
        run: python .github/workflows/ascii-art.py