# The idea of this workflow is to demonstrate how to use GitHub Actions secrets.
# The secret is stored in the repository settings under "Secrets and variables" -> "Actions".

name: Secrets Workflow
on: push

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}


jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Use secret
          run: echo "$GITHUB_TOKEN"
        
        - name: Check the secret sha 256sum
          run: |
                echo "The sha256sum of the secret is:"
                echo -n "$GITHUB_TOKEN" | sha256sum