name: Triggered Workflow

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  run-something:
    runs-on: ubuntu-latest
    steps:
      - name: Print the dispatch payload
        run: echo "Hello from repository_dispatch!"