name: Learn how to use github actions secrets
on: push

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}


jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Use secret
          run: echo "$GITHUB_TOKEN"
        
        - name: Check the secret sha 256sum
          run: |
                echo "The sha256sum of the secret is:"
                echo -n "$GITHUB_TOKEN" | sha256sum