name: Manual Trigger

on:
  workflow_dispatch:

jobs:
  manual_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow was triggered manually!"
      - run: echo "You can add more steps here to perform any actions you need."
  